Repository upscale-project/pono, pull requests merged in 2020-09, with the labels that each got.

#80 Fix copy-paste error in multiply overflow encoding in BTOR2
  frontends/btor2_encoder.cpp
  tests/encoders/inputs/btor2/mulo-test.btor2
  tests/encoders/test_btor2.cpp
Labels: bug, simple

#81 Fix copy paste error in uaddo encoding
  frontends/btor2_encoder.cpp
Labels: bug, simple

#75 Static cone-of-influence analysis
  core/prop.cpp
  core/prop.h
  core/ts.cpp
  core/ts.h
  engines/bmc.cpp
  engines/bmc.h
  engines/bmc_simplepath.cpp
  engines/bmc_simplepath.h
  engines/interpolantmc.cpp
  engines/interpolantmc.h
  engines/kinduction.cpp
  engines/kinduction.h
  engines/prover.cpp
  engines/prover.h
  options/options.cpp
  options/options.h
  samples/cone-of-influence-reduction/count2-redundancy-constraint-bad-unreachable.btor2
  samples/cone-of-influence-reduction/count2-redundancy-constraint-connection.btor2
  samples/cone-of-influence-reduction/count2-redundancy.btor2
  samples/cone-of-influence-reduction/count9-10-combined-redundancy.btor2
  samples/cone-of-influence-reduction/unconstrained-input.btor2
Labels: enhancement

#71 Add method to get a name for a term and use it for printing property
  core/prop.cpp
  core/prop.h
  core/ts.cpp
  core/ts.h
  pono.cpp
Labels: simple
