Repository upscale-project/pono, pull requests merged in 2020-07, with the labels that each got.

#50 add option to suppress witness printing
  options/defaults.h
  pono.cpp
Labels: enhancement, simple

#53 mc-interp: refactor
  engines/interpolantmc.cpp
  engines/interpolantmc.h
Labels: refactor

#51 Handle command line options in a separate PonoOptions class
  CMakeLists.txt
  core/proverresult.cpp
  core/proverresult.h
  engines/bmc.cpp
  engines/bmc.h
  engines/bmc_simplepath.cpp
  engines/bmc_simplepath.h
  engines/interpolantmc.cpp
  engines/interpolantmc.h
  engines/kinduction.cpp
  engines/kinduction.h
  engines/prover.cpp
  engines/prover.h
  options/defaults.h
  options/options.cpp
  options/options.h
  pono.cpp
Labels: enhancement, simple

#56 Keep track of constraints added to trans through add_constraints, add_invar, and constrain_inputs
  core/ts.cpp
  core/ts.h
Labels: simple

#40 Support an install target through cmake
  CMakeLists.txt
  cmake_uninstall.cmake.in
  core/fts.h
  core/prop.h
  core/ts.h
  core/unroller.h
  engines/bmc.h
  engines/bmc_simplepath.h
  engines/interpolantmc.h
  engines/kinduction.h
  engines/prover.h
  frontends/btor2_encoder.h
  frontends/coreir_encoder.cpp
  frontends/smv_encoder.cpp
  frontends/smv_encoder.h
  frontends/smv_node.h
  frontends/smvparser.y
  frontends/smvscanner.h
  pono.cpp
  printers/vcd_witness_printer.cpp
  tests/encoders/test_coreir.cpp
  tests/test_unroller.cpp
  utils/logger.cpp
Labels: refactor, simple

#62 Interpolant return result
  engines/interpolantmc.cpp
Labels: simple
