Repository upscale-project/pono, pull requests merged in 2020-08, with the labels that each got.

#54 Allow using a fresh solver in each engine
  .travis.yml
  CMakeLists.txt
  configure.sh
  contrib/setup-smt-switch.sh
  core/fts.cpp
  core/fts.h
  core/prop.cpp
  core/prop.h
  core/rts.h
  core/ts.cpp
  core/ts.h
  core/unroller.cpp
  core/unroller.h
  engines/bmc.cpp
  engines/bmc.h
  engines/bmc_simplepath.cpp
  engines/bmc_simplepath.h
  engines/interpolantmc.cpp
  engines/interpolantmc.h
  engines/kinduction.cpp
  engines/kinduction.h
  engines/prover.cpp
  engines/prover.h
  frontends/btor2_encoder.h
  frontends/smv_encoder.h
  python/pono_imp.pxd
  python/pono_imp.pxi
  smt/available_solvers.cpp
  smt/available_solvers.h
  tests/CMakeLists.txt
  tests/available_solvers.cpp
  tests/available_solvers.h
  tests/encoders/inputs/btor2/counter-true.btor
  tests/encoders/inputs/btor2/counter.btor
  tests/encoders/inputs/btor2/mem.btor
  tests/encoders/inputs/btor2/ridecore.btor
  tests/encoders/inputs/btor2/state2input.btor
  tests/encoders/test_btor2.cpp
  tests/encoders/test_coreir.cpp
  tests/encoders/test_encoder_inputs.h
  tests/test_btor2_ts_copy_equal.cpp
  tests/test_engines.cpp
  tests/test_ts.cpp
  tests/test_unroller.cpp
  tests/test_witness.cpp
  travis-scripts/download-cvc4.sh
Labels: complex, enhancement

#72 Add support for ~rst syntax for negative resets
  frontends/btor2_encoder.cpp
  pono.cpp
  samples/neg_rst_test.btor2
  samples/neg_rst_test.v
Labels: simple

#74 Fix in transition system copy constructor
  core/ts.cpp
Labels: bugfix, simple
