Repository upscale-project/pono, pull requests merged in 2021-01, with the labels that each got.

#164 Prover update 2
  CMakeLists.txt
  core/prop.cpp
  core/prop.h
  engines/bmc.cpp
  engines/bmc.h
  engines/bmc_simplepath.cpp
  engines/bmc_simplepath.h
  engines/ceg_prophecy_arrays.cpp
  engines/ceg_prophecy_arrays.h
  engines/cegar.h
  engines/ic3.cpp
  engines/ic3.h
  engines/ic3base.cpp
  engines/ic3base.h
  engines/ic3ia.cpp
  engines/ic3ia.h
  engines/interpolantmc.cpp
  engines/interpolantmc.h
  engines/kinduction.cpp
  engines/kinduction.h
  engines/mbic3.cpp
  engines/mbic3.h
  engines/msat_ic3ia.cpp
  engines/msat_ic3ia.h
  engines/prover.cpp
  engines/prover.h
  modifiers/mod_init_prop.h
  modifiers/prop_monitor.h
  pono.cpp
  python/pono_imp.pxd
  python/pono_imp.pxi
  tests/encoders/test_btor2.cpp
  tests/encoders/test_smv.cpp
  tests/python/test_engines.py
  tests/python/test_printers.py
  tests/test_ceg_prophecy_arrays.cpp
  tests/test_control_signal_modifiers.cpp
  tests/test_engines.cpp
  tests/test_ic3.cpp
  tests/test_ic3ia.cpp
  tests/test_ts.cpp
  tests/test_uf.cpp
  tests/test_utils.cpp
  tests/test_witness.cpp
  utils/make_provers.cpp
  utils/make_provers.h
Labels: refactor

#168 Fixes for msat-ic3ia after prover-update
  engines/msat_ic3ia.cpp
  tests/test_msat_ic3ia.cpp
Labels: simple

#171 Update unroller
  CMakeLists.txt
  core/adaptive_unroller.cpp
  core/adaptive_unroller.h
  core/unroller.cpp
  core/unroller.h
  engines/ceg_prophecy_arrays.h
  engines/prover.h
  tests/test_unroller.cpp
Labels: refactor

#172 Additional options for get_predicates
  engines/ic3ia.cpp
  tests/test_term_analysis.cpp
  utils/term_analysis.cpp
  utils/term_analysis.h
Labels: simple

#175 Refactor inductive generalization
  engines/ic3.cpp
  engines/ic3.h
  engines/ic3base.cpp
  engines/ic3base.h
  engines/mbic3.cpp
  engines/mbic3.h
Labels: refactor, simple

#176 simplify unroller interface
  core/functional_unroller.cpp
  core/functional_unroller.h
  core/unroller.cpp
  core/unroller.h
  engines/prover.cpp
  python/pono_imp.pxd
  python/pono_imp.pxi
  tests/python/test_unroller.py
  tests/test_modifiers.cpp
  tests/test_unroller.cpp
Labels: refactor

#177 Improvements and default implementation of inductive_generalization
  engines/ic3.cpp
  engines/ic3.h
  engines/ic3base.cpp
  engines/ic3base.h
  engines/ic3ia.cpp
  engines/ic3ia.h
  engines/mbic3.cpp
  engines/mbic3.h
Labels: enhancement

#180 Transfer property as BOOL -- helps for sort aliasing solvers
  engines/ceg_prophecy_arrays.cpp
  engines/msat_ic3ia.cpp
  engines/prover.cpp
Labels: simple

#184 minor: reset solver after each propagate phase
  engines/ic3base.cpp
Labels: simple

#185 IC3IA: do a single iteration of reduction in reduce_predicates
  modifiers/implicit_predicate_abstractor.cpp
Labels: simple

#190 Various minor fixes
  engines/ic3base.cpp
  engines/ic3ia.cpp
  engines/msat_ic3ia.cpp
Labels: simple

#193 Add an option to assume the property in the pre-state
  core/ts.cpp
  core/ts.h
  modifiers/mod_init_prop.h
  options/options.cpp
  options/options.h
  pono.cpp
Labels: simple

#197 Temporary configuration fix for CegProphecyArrays
  pono.cpp
  smt/available_solvers.cpp
  smt/available_solvers.h
Labels: bugfix

#199 Fixes mismatched push/pop in encoder and sets solver options up front
  engines/ic3.cpp
  frontends/smv_encoder.cpp
  smt/available_solvers.cpp
  tests/test_ceg_prophecy_arrays.cpp
  tests/test_ic3.cpp
  tests/test_ic3ia.cpp
Labels: simple

#196 CEGAR loop to abstract values
  CMakeLists.txt
  core/ts.cpp
  core/ts.h
  engines/ceg_prophecy_arrays.cpp
  engines/ceg_prophecy_arrays.h
  engines/cegar_values.cpp
  engines/cegar_values.h
  engines/ic3base.cpp
  engines/ic3base.h
  engines/prover.cpp
  engines/prover.h
  modifiers/mod_init_prop.h
  options/options.cpp
  options/options.h
  pono.cpp
  python/pono_imp.pxd
  python/pono_imp.pxi
  tests/CMakeLists.txt
  tests/python/test_ts.py
  tests/test_cegar_values.cpp
  utils/fcoi.cpp
  utils/make_provers.cpp
  utils/make_provers.h
  utils/ts_manipulation.cpp
  utils/ts_manipulation.h
Labels: enhancement

#200 Fix: move refinement so that one-step CEXs are refined
  engines/ic3base.cpp
Labels: bugfix, simple

#203 Do not increment i after refinement
  engines/ic3base.cpp
  tests/test_ic3ia.cpp
Labels: bugfix

#202 Add property in get_frame_term
  engines/ic3base.cpp
Labels: bugfix

#206 Minor: Don't re-add property to invariant frame
  engines/ic3base.cpp
Labels: simple

#201 Fix push/pop mismatch in array_axioms_refiner
  refiners/array_axiom_enumerator.cpp
Labels: bugfix, simple

#208 Create option for cutoff value of CegarValues
  engines/cegar_values.cpp
  options/options.cpp
  options/options.h
Labels: enhancement

#209 Ic3ia: exclude unused symbols from cubes
  engines/ceg_prophecy_arrays.cpp
  engines/ic3ia.cpp
  modifiers/implicit_predicate_abstractor.cpp
Labels: simple

#211 Use witness length when refining in CegProphecyArrays
  engines/ceg_prophecy_arrays.cpp
Labels: simple

#213 De-duplicate the options code in main
  pono.cpp
Labels: refactor, structural

#210 Disable witness generation/printing by default
  options/options.cpp
  options/options.h
  pono.cpp
  scripts/parallel_pono.py
Labels: simple

#215 Minor fix to comments in IC3Base::reaches_bad
  engines/ic3base.cpp
Labels: simple

#216 Declare ProofGoalQueue in header
  engines/ic3base.cpp
  engines/ic3base.h
Labels: refactor, structural

#219 Turn off assume-prop in pre-state by default
  modifiers/mod_ts_prop.cpp
  modifiers/mod_ts_prop.h
  options/options.cpp
  options/options.h
Labels: simple

#224 Fix for constraints after promoting inputvars
  core/ts.cpp
  core/ts.h
  modifiers/mod_ts_prop.cpp
  modifiers/mod_ts_prop.h
  modifiers/prop_monitor.h
  pono.cpp
  tests/CMakeLists.txt
  tests/test_promote_inputvars.cpp
Labels: bugfix

#226 Use default inductive_generalization for option 0 in mbic3
  engines/mbic3.cpp
Labels: bugfix

#222 Allow f and F as variable names in SMV frontend
  frontends/smvparser.l
  frontends/smvparser.y
Labels: simple

#223 Remove set from SMV grammar
  frontends/smvparser.l
  frontends/smvparser.y
Labels: simple

#228 Maintain contract that witness length refers to number of transitions
  engines/ceg_prophecy_arrays.cpp
  engines/ic3base.cpp
Labels: bugfix, simple

#145 WIP: SyGuS PDR
  CMakeLists.txt
  engines/syguspdr.cpp
  engines/syguspdr.h
  modifiers/op_abstractor.cpp
  modifiers/op_abstractor.h
  options/options.cpp
  options/options.h
  samples/sygus-pdr/bvadd-cond.btor2
  samples/sygus-pdr/bvadd-simple.btor2
  samples/sygus-pdr/bvadd.btor2
  samples/sygus-pdr/cal39.btor2
  samples/sygus-pdr/mul4.btor2
  samples/sygus-pdr/trans.btor
  samples/sygus-pdr/two-cnt-false.btor
  samples/sygus-pdr/two-cnt-true-2.btor
  samples/sygus-pdr/two-cnt-true.btor
  tests/CMakeLists.txt
  tests/test_partial_model.cpp
  utils/container_shortcut.h
  utils/make_provers.cpp
  utils/partial_model.cpp
  utils/partial_model.h
  utils/str_util.cpp
  utils/str_util.h
  utils/sygus_ic3formula_helper.cpp
  utils/sygus_ic3formula_helper.h
  utils/sygus_predicate_constructor.cpp
  utils/sygus_predicate_constructor.h
  utils/syntax_analysis.cpp
  utils/syntax_analysis.h
  utils/syntax_analysis_common.cpp
  utils/syntax_analysis_common.h
  utils/syntax_analysis_walker.cpp
  utils/syntax_analysis_walker.h
Labels: enhancement

#230 Ic3ia reset solver
  engines/ceg_prophecy_arrays.cpp
  engines/ic3ia.cpp
  engines/ic3ia.h
Labels: enhancement, refactor, simple

#232 Refactor CEG_PROPH
  engines/ceg_prophecy_arrays.cpp
Labels: refactor, simple

#231 UF operator abstraction
  CMakeLists.txt
  engines/cegar_ops_uf.cpp
  engines/cegar_ops_uf.h
  modifiers/ops_abstractor.cpp
  modifiers/ops_abstractor.h
  options/options.cpp
  options/options.h
  pono.cpp
  tests/CMakeLists.txt
  tests/test_cegar_ops_uf.cpp
  utils/make_provers.cpp
  utils/make_provers.h
Labels: enhancement

#239 Adjust error vs unknown result
  engines/ic3base.cpp
  pono.cpp
Labels: simple

#227 Ic3 split bits
  CMakeLists.txt
  engines/ic3bits.cpp
  engines/ic3bits.h
  options/options.cpp
  options/options.h
  smt/available_solvers.cpp
  tests/CMakeLists.txt
  tests/test_ic3bits.cpp
  utils/make_provers.cpp
Labels: enhancement, simple

#241 Limit cegar bv width
  engines/cegar_ops_uf.h
  modifiers/ops_abstractor.cpp
  modifiers/ops_abstractor.h
  options/options.cpp
  options/options.h
  utils/make_provers.cpp
Labels: enhancement, simple

#141 Add basic IC3SA implementation
  CMakeLists.txt
  core/functional_unroller.cpp
  core/ts.cpp
  core/ts.h
  engines/ceg_prophecy_arrays.cpp
  engines/ic3sa.cpp
  engines/ic3sa.h
  options/options.cpp
  options/options.h
  pono.cpp
  samples/uv_example.btor2
  samples/uv_example.v
  samples/uvw_example.btor2
  samples/uvw_example.v
  smt/available_solvers.cpp
  tests/CMakeLists.txt
  tests/test_ic3sa.cpp
  tests/test_unroller.cpp
  tests/test_utils.cpp
  tests/test_walkers.cpp
  utils/fcoi.cpp
  utils/fcoi.h
  utils/logger.cpp
  utils/logger.h
  utils/make_provers.cpp
  utils/term_analysis.cpp
  utils/term_analysis.h
  utils/term_walkers.cpp
  utils/term_walkers.h
  xp2.btor2
  xp2.v
Labels: enhancement

#240 Various improvements to IC3SA
  engines/cegar_ops_uf.cpp
  engines/ic3base.cpp
  engines/ic3sa.cpp
  engines/ic3sa.h
  options/options.cpp
  options/options.h
  pono.cpp
  utils/make_provers.cpp
  utils/term_analysis.cpp
  utils/term_analysis.h
Labels: enhancement
